export const LINKS = [
  {
    label: "Nosotros",
    href: "about",
  },
  {
    label: "Servicios",
    href: "services",
  },
  {
    label: "Contacto",
    href: "contact",
  },
];

export const SERVICES = [
  {
    label: "Mantenimiento general",
    href: "general",
    image: "/motor.jpg",
    shortDesc: "Revisión y mantenimiento preventivo para tu vehículo.",
    longDesc: "Nuestro servicio de mantenimiento general incluye revisión de fluidos, filtros, correas, niveles y componentes esenciales para asegurar el óptimo funcionamiento y prolongar la vida útil de tu auto.",
    suggestedProducts: ["Aceite multigrado", "Filtro de aire", "Filtro de aceite"],
  },
  {
    label: "Frenos",
    href: "brakes",
    image: "/frenos.jpg",
    shortDesc: "Inspección y reparación de frenos para tu seguridad.",
    longDesc: "Realizamos diagnóstico, cambio de pastillas, discos, líquido y ajuste de frenos para garantizar una respuesta segura y eficiente en cualquier situación.",
    suggestedProducts: ["Pastillas de freno", "Líquido de frenos", "Discos de freno"],
  },
  {
    label: "Cambio de aceite",
    href: "oil",
    image: "/aceite.jpg",
    shortDesc: "Cambio de aceite y filtro para un motor saludable.",
    longDesc: "Utilizamos aceites y filtros de alta calidad para proteger el motor de tu vehículo, mejorando su rendimiento y prolongando su vida útil.",
    suggestedProducts: ["Aceite sintético", "Filtro de aceite", "Aditivo para motor"],
  },
  {
    label: "Amortiguación",
    href: "shock",
    image: "/suspension.jpg",
    shortDesc: "Revisión y cambio de amortiguadores y suspensión.",
    longDesc: "Inspeccionamos y reemplazamos amortiguadores, resortes y componentes de suspensión para una conducción suave y segura.",
    suggestedProducts: ["Amortiguadores", "Bujes de suspensión", "Resortes"],
  },
  {
    label: "Scanner",
    href: "scanner",
    image: "/escaner.jpg",
    shortDesc: "Diagnóstico computarizado de fallas electrónicas.",
    longDesc: "Contamos con equipos de última generación para detectar y solucionar fallas electrónicas en tu vehículo de manera precisa y rápida.",
    suggestedProducts: ["Scanner OBDII", "Sensor de oxígeno", "Batería"],
  },
  {
    label: "Reparación de motores",
    href: "engine",
    image: "/motor.jpg",
    shortDesc: "Reparación y ajuste de motores a gasolina y diésel.",
    longDesc: "Ofrecemos reparación integral de motores, desde cambio de empaques hasta reconstrucción completa, asegurando el mejor desempeño.",
    suggestedProducts: ["Empaques de motor", "Aceite de motor", "Correa de distribución"],
  },
  {
    label: "Reparación de caja mecanica",
    href: "gear",
    image: "/caja.jpg",
    shortDesc: "Diagnóstico y reparación de cajas mecánicas.",
    longDesc: "Solucionamos problemas de transmisión manual, reemplazo de piezas y ajuste para un cambio de marchas suave y preciso.",
    suggestedProducts: ["Kit de embrague", "Aceite para transmisión", "Sincronizadores"],
  },
];

export const PRODUCTS = [
  {
    id: 1,
    name: "Aceite sintético 5W-30",
    image: "/aceite.jpg",
    stock: 25,
    price: 120000,
  },
  {
    id: 2,
    name: "Filtro de aceite Bosch",
    image: "/aceite.jpg",
    stock: 40,
    price: 25000,
  },
  {
    id: 3,
    name: "Filtro de aire Fram",
    image: "/motor.jpg",
    stock: 30,
    price: 18000,
  },
  {
    id: 4,
    name: "Pastillas de freno delanteras",
    image: "/frenos.jpg",
    stock: 15,
    price: 65000,
  },
  {
    id: 5,
    name: "Líquido de frenos DOT4",
    image: "/frenos.jpg",
    stock: 50,
    price: 12000,
  },
  {
    id: 6,
    name: "Disco de freno ventilado",
    image: "/frenos.jpg",
    stock: 10,
    price: 90000,
  },
  {
    id: 7,
    name: "Amortiguador delantero",
    image: "/suspension.jpg",
    stock: 12,
    price: 110000,
  },
  {
    id: 8,
    name: "Buje de suspensión",
    image: "/suspension.jpg",
    stock: 35,
    price: 15000,
  },
  {
    id: 9,
    name: "Resorte de suspensión",
    image: "/suspension.jpg",
    stock: 8,
    price: 70000,
  },
  {
    id: 10,
    name: "Scanner OBDII universal",
    image: "/escaner.jpg",
    stock: 20,
    price: 85000,
  },
  {
    id: 11,
    name: "Sensor de oxígeno NGK",
    image: "/escaner.jpg",
    stock: 18,
    price: 60000,
  },
  {
    id: 12,
    name: "Batería 12V 60Ah",
    image: "/escaner.jpg",
    stock: 14,
    price: 180000,
  },
  {
    id: 13,
    name: "Empaques de motor completo",
    image: "/motor.jpg",
    stock: 7,
    price: 95000,
  },
  {
    id: 14,
    name: "Aceite de motor 20W-50",
    image: "/aceite.jpg",
    stock: 22,
    price: 110000,
  },
  {
    id: 15,
    name: "Correa de distribución",
    image: "/correa.jpg",
    stock: 16,
    price: 40000,
  },
  {
    id: 16,
    name: "Kit de embrague",
    image: "/embrague.jpg",
    stock: 9,
    price: 210000,
  },
  {
    id: 17,
    name: "Aceite para transmisión",
    image: "/caja.jpg",
    stock: 28,
    price: 75000,
  },
  {
    id: 18,
    name: "Sincronizadores de caja",
    image: "/sincro.jpg",
    stock: 6,
    price: 95000,
  },
  {
    id: 19,
    name: "Filtro de cabina",
    image: "/motor.jpg",
    stock: 32,
    price: 20000,
  },
  {
    id: 20,
    name: "Aditivo para motor Liqui Moly",
    image: "/aceite.jpg",
    stock: 13,
    price: 35000,
  },
  {
    id: 21,
    name: "Filtro de gasolina",
    image: "/motor.jpg",
    stock: 27,
    price: 22000,
  },
  {
    id: 22,
    name: "Bujía NGK Iridium",
    image: "/motor.jpg",
    stock: 44,
    price: 18000,
  },
  {
    id: 23,
    name: "Correa de accesorios",
    image: "/correa.jpg",
    stock: 19,
    price: 25000,
  },
  {
    id: 24,
    name: "Kit de distribución",
    image: "/correa.jpg",
    stock: 11,
    price: 120000,
  },
  {
    id: 25,
    name: "Filtro de combustible Bosch",
    image: "/motor.jpg",
    stock: 21,
    price: 26000,
  },
  {
    id: 26,
    name: "Aceite sintético 0W-20",
    image: "/aceite.jpg",
    stock: 17,
    price: 130000,
  },
  {
    id: 27,
    name: "Pastillas de freno traseras",
    image: "/frenos.jpg",
    stock: 14,
    price: 60000,
  },
  {
    id: 28,
    name: "Disco de freno sólido",
    image: "/frenos.jpg",
    stock: 9,
    price: 80000,
  },
  {
    id: 29,
    name: "Amortiguador trasero",
    image: "/suspension.jpg",
    stock: 10,
    price: 105000,
  },
  {
    id: 30,
    name: "Buje de barra estabilizadora",
    image: "/suspension.jpg",
    stock: 24,
    price: 12000,
  },
  {
    id: 31,
    name: "Resorte trasero",
    image: "/suspension.jpg",
    stock: 7,
    price: 65000,
  },
  {
    id: 32,
    name: "Scanner OBDII avanzado",
    image: "/escaner.jpg",
    stock: 8,
    price: 120000,
  },
  {
    id: 33,
    name: "Sensor de temperatura",
    image: "/escaner.jpg",
    stock: 18,
    price: 30000,
  },
  {
    id: 34,
    name: "Batería 12V 70Ah",
    image: "/escaner.jpg",
    stock: 10,
    price: 200000,
  },
  {
    id: 35,
    name: "Empaques de culata",
    image: "/motor.jpg",
    stock: 6,
    price: 40000,
  },
  {
    id: 36,
    name: "Aceite de motor 10W-40",
    image: "/aceite.jpg",
    stock: 20,
    price: 115000,
  },
  {
    id: 37,
    name: "Correa de alternador",
    image: "/correa.jpg",
    stock: 15,
    price: 23000,
  },
  {
    id: 38,
    name: "Kit de embrague reforzado",
    image: "/embrague.jpg",
    stock: 5,
    price: 250000,
  },
  {
    id: 39,
    name: "Aceite para caja automática",
    image: "/caja.jpg",
    stock: 13,
    price: 95000,
  },
  {
    id: 40,
    name: "Sincronizadores reforzados",
    image: "/sincro.jpg",
    stock: 4,
    price: 120000,
  },
  {
    id: 41,
    name: "Filtro de aire deportivo",
    image: "/motor.jpg",
    stock: 12,
    price: 35000,
  },
  {
    id: 42,
    name: "Aditivo para gasolina",
    image: "/aceite.jpg",
    stock: 16,
    price: 18000,
  },
  {
    id: 43,
    name: "Filtro de cabina premium",
    image: "/motor.jpg",
    stock: 14,
    price: 25000,
  },
  {
    id: 44,
    name: "Bujía Bosch Platinum",
    image: "/motor.jpg",
    stock: 30,
    price: 20000,
  },
  {
    id: 45,
    name: "Correa de dirección",
    image: "/correa.jpg",
    stock: 11,
    price: 21000,
  },
  {
    id: 46,
    name: "Kit de distribución premium",
    image: "/correa.jpg",
    stock: 7,
    price: 150000,
  },
  {
    id: 47,
    name: "Filtro de combustible premium",
    image: "/motor.jpg",
    stock: 10,
    price: 32000,
  },
  {
    id: 48,
    name: "Aceite sintético 10W-30",
    image: "/aceite.jpg",
    stock: 18,
    price: 125000,
  },
  {
    id: 49,
    name: "Pastillas de freno cerámicas",
    image: "/frenos.jpg",
    stock: 8,
    price: 90000,
  },
  {
    id: 50,
    name: "Disco de freno perforado",
    image: "/frenos.jpg",
    stock: 6,
    price: 110000,
  },
];
